### PR TITLE
Validate cookiecutter arguments

### LINKED ISSUE #19: Ingest template accepts invalid inputs
## Describe the bug
The ingest Cookiecutter template does not perform any sort of validation on user inputs to the given prompts, resulting in crashes during Cookiecutter code hooks.

## Steps to Reproduce

To reproduce just run `make cookies` and insert dashes `-` in the `module` prompt. This will result in an invalid python module name and cause errors.

## Expected behavior
If the user inputs bad values the cookiecutter prompt should crash immediately.

## Screenshots
image

## Proposed solution

Add a typer CLI / interface to the cookiecutter to validate args as they are passed in. This would allow for immediate validation and even allow us to prompt for correct values without having to resubmit the other prompts.

### PR DESCRIPTION
**Pull request by maxwellevin**
This PR wraps the cookiecutter template in a typer CLI to allow for better validation and description of the inputs.

- [x] Add cookiecutter CLI wrapper script
- [x] Update instructions on how to run it 
- [x] Add tests to verify template generation

Merging this fixes #19

### CODE REVIEW

**Comment by maxwellevin** [comment]
Tests passing previously, but I'm going to re-run them here to see if the they are affected by #24

**Comment by maxwellevin** [comment]
Tests still passing

**Review by jmcvey3 — COMMENTED** [review]
How exactly does one access the "help" string from a user standpoint? I didn't see that in the docs

**Review by jmcvey3 — COMMENTED** [review]
I also managed to make it error, and I'll send you that screenshot by chat

**Review by jmcvey3 — COMMENTED** [review]
Otherwise looks good!

**Comment by maxwellevin** [comment]
Thanks @jmcvey3 for the feedback and edge case. I think I've addressed it now.
- Added docs on the `python templates/generate.py` command
- Improved validation for the module and classname prompts

Error message you showed before:
Screenshot (251)

New behavior:
image

**Comment by maxwellevin** [comment]
@jmcvey3 do you think this is ready to merge?

**Comment by jmcvey3** [comment]
> @jmcvey3 do you think this is ready to merge?

Yep, looks good.

**Pull request merged**
