### PR TITLE
Multiple pipeline dispatch

### PR DESCRIPTION
**Pull request by maxwellevin**
This PR adds support for dispatching multiple pipelines for each input key.

Closes https://github.com/tsdat/tsdat/issues/107

### CODE REVIEW

**Comment by maxwellevin** [comment]
@jmcvey3 is this working when you run it locally? If so I think we can merge it now

**Comment by jmcvey3** [comment]
Yes, but writing a test for this was on my list

**Review by maxwellevin — COMMENTED** [review]
changes look good to me

**Comment by maxwellevin** [comment]
@jmcvey3 you can merge this if it is ready now.

**Pull request merged**
